name:                pacrd-migrate
version:             0.1.0
#synopsis:
#description:
github:              armory/pacrd-migrate
license:             BSD3
author:              Fernando Freire
maintainer:          fernando.freire@armory.io
copyright:           2021 Armory.io
category:            CLI
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - text
  - yaml
  - aeson
  - directory

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-partial-type-signatures
  - -fno-warn-name-shadowing
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-incomplete-patterns
  - -fwrite-ide-info
  - -hiedir=.hie

default-extensions:
  - BangPatterns
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables
  - TemplateHaskell

executables:
  pacrd-migrate:
    source-dirs:      src
    main:             Main.hs
