apiVersion: pacrd.armory.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  email: fernando.freire@armory.io
---
apiVersion: pacrd.armory.io/v1alpha1
kind: Pipeline
metadata:
  name: lol
spec:
  application: app
  description: this is a pipeline
  expectedArtifacts:
    - id: &id pacrd-image
      displayName: &name Public PaCRD Image
      matchArtifact:
        type: docker/image
        properties:
          name: armory/pacrd
          artifactAccount: docker-registry
  stages:
    - type: wait
      properties:
        duration: foo
